version: '1'

services:
  db:
    image: mariadb:10.9
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: RankUpDB
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      APACHE_HTTP_PORT_NUMBER: 8090
    networks:
      - backend
    restart: always

  backend:
    image: backend:latest
    container_name: backend
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - backend
    restart: unless-stopped
    


volumes:
  db_data:

networks:
  backend: